### ISSUE TITLE
Arduino Due + ILI9341 TFT + Adafruit libs: Arduino SPI extended mode does not work

### ISSUE THREAD

**Issue by shiftleftplusone** [arduino/ArduinoCore-sam#84]
Arduino Due + ILI9341 TFT + Adafruit libs (IDE 1.6.3): Arduino SPI extended mode does not work:
when I start the test sketch by the following code, the program shows no TFT output, screen is light grey, just the Serial output:

```
// Adafruit ILI9340 / ILI9341

#include "SPI.h"
#include "Adafruit_GFX.h"
#include "Adafruit_ILI9340.h"

#if defined(__SAM3X8E__)
    #undef __FlashStringHelper::F(string_literal)
    #define F(string_literal) string_literal
#endif

#define    tft_cs     10
#define    tft_dc      9
#define    tft_rst     8

Adafruit_ILI9340 tft = Adafruit_ILI9340(tft_cs, tft_dc, tft_rst);

void setup() { 
  Serial.begin(9600);
  // Setup the LCD
  SPI.begin(tft_cs);
  SPI.setClockDivider(tft_cs,21); // 21==4MHz (standard)
  tft.begin();
  tft.setRotation(3);
  tft.setTextColor(ILI9340_WHITE); tft.setTextSize(1);  
  Serial.println("tft started");
}

```

nevertheless, in the normal (AVR?) mode it works:

```
// Adafruit ILI9340 / ILI9341

#include "SPI.h"
#include "Adafruit_GFX.h"
#include "Adafruit_ILI9340.h"

#if defined(__SAM3X8E__)
    #undef __FlashStringHelper::F(string_literal)
    #define F(string_literal) string_literal
#endif

#define    tft_cs     10
#define    tft_dc      9
#define    tft_rst     8

Adafruit_ILI9340 tft = Adafruit_ILI9340(tft_cs, tft_dc, tft_rst);

void setup() { 
  Serial.begin(9600);
  // Setup the LCD
  tft.begin();
  tft.setRotation(3);
  tft.setTextColor(ILI9340_WHITE); tft.setTextSize(1);  
  Serial.println("tft started");
}
```

Is it an Arduino IDE SPI issue?

**Comment by cmaglie** [comment]
@shiftleftplusone, long time passed, I don't know if in the meantime you solved the problem.

With the "Extended SPI" API there are many problems:
1) The CS pin is controlled directly by the hardware (and no more by the lib through `digitalWrite`) but some SPI devices requires "non-standard" toggling of CS pin (that is not supported with Extended SPI hardware)
2) Because of the above, the LCD library should use the Extended functions, because the CS pin is no longer available as GPIO
3) There is no support for transactions

for those reason the "Extended API" has been deprecated, in favor of the standar SPI API.

https://www.arduino.cc/en/Reference/DueExtendedSPI
